name: trackapi-infra
services:
  dynamodb:
    container_name: dynamodb
    hostname: dynamodb
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports:
      - 8080:8000
  dynamodb-init:
    container_name: dynamodb-init
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    env_file:
      - ../../.env.local
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for DynamoDB to start...";
        sleep 3;        
        python app/load_shipments.py
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
