name: trackapi
services:
  track_api:
    container_name: track_api
    hostname: track_api
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    ports:
      - 8000:80
    env_file:
      - ../../.env.local
    restart: unless-stopped
  dynamodb:
    container_name: dynamodb
    hostname: dynamodb
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
  dynamodb-init:
    container_name: dynamodb-init
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    env_file:
      - ../../.env.local
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for DynamoDB to start...";
        sleep 3;        
        python app/load_shipments.py
  redis:
    container_name: redis
    hostname: redis
    image: redis
